### ISSUE TITLE
Glibc error with 1.1.6

### ISSUE THREAD

**Issue by KimonLHi** [SauceLLC/sauce4zwift#119]
After auto upgrading on Linux to Strava sauce 1.1.6, app image will not start and quits with glibc error as attached 

I'm on Ubuntu 22.04.4

![IMG-20240626-WA0011](https://github.com/SauceLLC/sauce4zwift/assets/173972298/16ceb11b-601a-4d80-8a6a-4b8f2188e616)

**Comment by mayfield** [comment]
Sorry about that, I forgot I need to build linux in a docker container with a more backwards compat host.  I updated the release manually for future linux user updates but you'll need to grab the file by hand since you are already affected.  Here's the link...

https://github.com/SauceLLC/sauce4zwift-releases/releases/download/v1.1.6/sauce4zwift-1.1.6.AppImage

**Comment by KimonLHi** [comment]
I'm still getting the same error -- should i wait for 1.1.7?

![WhatsApp Image 2024-06-27 at 13 37 44](https://github.com/SauceLLC/sauce4zwift/assets/173972298/9e3dfcc8-ce48-4e79-92be-0afc0e49fb2a)

**Comment by mayfield** [comment]
3rd times a charm, try this: https://github.com/SauceLLC/sauce4zwift-releases/releases/download/v1.1.6/sauce4zwift-1.1.6.AppImage

**Comment by KimonLHi** [comment]
great success! thank you.
